import type { Campaign, Contact, Template, OutboundMessage, ConversationReply, SuppressionNumber, DashboardKPIs, AppSettings } from '../types';
export const text = (v: unknown): string => typeof v === 'string' ? v : typeof v === 'number' && Number.isFinite(v) ? String(v) : '';
export const lower = (v: unknown): string => text(v).toLowerCase();
export const object = (v: unknown): Record<string, any> => v !== null && typeof v === 'object' && !Array.isArray(v) ? v as Record<string, any> : {};
export const number = (v: unknown): number => (typeof v === 'number' || typeof v === 'string') && Number.isFinite(Number(v)) ? Math.max(0, Number(v)) : 0;
export const array = (v: unknown): any[] => Array.isArray(v) ? v.filter(x => x !== null && typeof x === 'object' && !Array.isArray(x)) : [];
export const validUUID = (v: unknown): boolean => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(text(v));
export const defaults: AppSettings = { api_base_url: '', n8n_webhook_url: '', n8n_api_key: '', whatsapp_session_status: 'disconnected', whatsapp_phone: '', whatsapp_name: '', default_sending_interval: 120, default_timezone: 'Asia/Karachi', allowed_sending_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], default_start_time: '09:00', default_end_time: '17:00' };
export function normalizeStats(value: unknown): DashboardKPIs {
 const v=object(value);
 return { total_campaigns:number(v.total_campaigns),active_campaigns:number(v.active_campaigns),total_contacts:number(v.total_contacts),queued_messages:number(v.queued_messages ?? v.queued),sent_messages:number(v.sent_messages ?? v.sent),delivered_messages:number(v.delivered_messages ?? v.delivered),read_messages:number(v.read_messages ?? v.read),replied_messages:number(v.replied_messages ?? v.replied),failed_messages:number(v.failed_messages ?? v.failed),opted_out_contacts:number(v.opted_out_contacts ?? v.opted_out) };
}
export function normalizeCampaign(value: unknown, statistics?: unknown): Campaign {
 const v=object(value),s=object(statistics ?? v.statistics ?? v.stats); const k=normalizeStats(s);
 return { id:text(v.id ?? v.campaignId),name:text(v.name) || 'Unnamed campaign',status:(text(v.status)||'unknown') as Campaign['status'],template_id:text(v.template_id),template_name:text(v.template_name) || 'Campaign template',template:text(v.template),total_contacts:number(s.total_contacts ?? v.total_contacts),queued_count:number(s.queued ?? s.queued_count ?? v.queued_count),sent_count:number(s.sent ?? s.sent_count ?? v.sent_count),delivered_count:number(s.delivered ?? s.delivered_count ?? v.delivered_count),read_count:number(s.read ?? s.read_count ?? v.read_count),replied_count:number(s.replied ?? s.replied_count ?? v.replied_count),failed_count:number(s.failed ?? s.failed_count ?? v.failed_count),opted_out_count:number(s.opted_out ?? s.opted_out_count ?? v.opted_out_count ?? k.opted_out_contacts),sending_interval:number(v.send_interval_seconds ?? v.sending_interval) || 120,allowed_days:Array.isArray(v.allowed_days)?v.allowed_days.map(text).filter(Boolean):defaults.allowed_sending_days,start_time:text(v.sending_start_time ?? v.start_time).slice(0,5)||'09:00',end_time:text(v.sending_end_time ?? v.end_time).slice(0,5)||'17:00',timezone:text(v.timezone)||'Asia/Karachi',created_at:text(v.created_at),updated_at:text(v.updated_at) };
}
export function normalizeContact(value: unknown): Contact { const v=object(value);return {id:text(v.id),name:text(v.name)||text(v.first_name)||text(v.phone)||'Contact',first_name:text(v.first_name),company:text(v.company),phone:text(v.phone),email:text(v.email),city:text(v.city),industry:text(v.industry),status:(text(v.status)||'unknown') as Contact['status'],created_at:text(v.created_at),campaign_ids:Array.isArray(v.campaign_ids)?v.campaign_ids.map(text):validUUID(v.campaign_id)?[text(v.campaign_id)]:[]}; }
export function normalizeTemplate(value: unknown): Template {const v=object(value),content=text(v.content ?? v.body ?? v.template);return {id:text(v.id ?? v.templateId),name:text(v.name)||'Unnamed template',content,variables:Array.isArray(v.variables)?v.variables.map(text):[...new Set(Array.from(content.matchAll(/\{\{\s*([a-z_]+)\s*\}\}/g),m=>m[1]))],category:text(v.category),created_at:text(v.created_at),updated_at:text(v.updated_at)};}
export function normalizeMessage(value: unknown, campaignId?: string): OutboundMessage { const v=object(value);return {id:text(v.id),campaign_id:text(v.campaign_id)||campaignId,campaign_name:text(v.campaign_name),contact_id:text(v.contact_id),contact_name:text(v.contact_name ?? v.name)||text(v.phone)||'Contact',company:text(v.company),phone:text(v.phone),message_text:text(v.message_text ?? v.personalized_message ?? v.message),status:(text(v.status)||'unknown') as OutboundMessage['status'],sent_at:text(v.sent_at),delivered_at:text(v.delivered_at),read_at:text(v.read_at),error_message:text(v.error_message ?? v.error)}; }
export function normalizeReplies(value: unknown): ConversationReply[] {const groups=new Map<string,ConversationReply>();for(const raw of array(value)){const v=object(raw);if(Array.isArray(v.messages)){groups.set(text(v.id),{id:text(v.id),contact_id:text(v.contact_id),contact_name:text(v.contact_name)||text(v.phone)||'Contact',company:text(v.company),phone:text(v.phone),last_message:text(v.last_message),unread_count:number(v.unread_count),updated_at:text(v.updated_at),messages:array(v.messages).map(m=>({id:text(m.id),sender:['agent','system'].includes(text(m.sender))?m.sender:'contact',text:text(m.text ?? m.message),timestamp:text(m.timestamp ?? m.received_at)}))});continue;}const key=text(v.campaign_id)+':'+text(v.phone);const group=groups.get(key)??{id:key,contact_id:text(v.contact_id),contact_name:text(v.contact_name)||text(v.phone)||'Contact',company:text(v.company),phone:text(v.phone),last_message:'',unread_count:0,updated_at:'',messages:[]};group.messages.push({id:text(v.id),sender:'contact',text:text(v.message),timestamp:text(v.received_at)});groups.set(key,group);}return [...groups.values()].map(g=>{g.messages.sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const last=g.messages.at(-1);return {...g,last_message:last?.text||g.last_message,updated_at:last?.timestamp||g.updated_at};});}
export function normalizeSuppression(value: unknown): SuppressionNumber {const v=object(value);return {id:text(v.id),phone:text(v.phone),contact_name:text(v.contact_name),reason:(text(v.reason)||'manual') as SuppressionNumber['reason'],added_at:text(v.added_at ?? v.created_at),added_by:text(v.added_by)||'Operator',notes:text(v.notes)};}

export function formatDate(value:unknown,kind:'date'|'time'|'full'='full'):string{const v=text(value);if(!v||!Number.isFinite(Date.parse(v)))return '—';const d=new Date(v);return kind==='date'?d.toLocaleDateString():kind==='time'?d.toLocaleTimeString():d.toLocaleString();}
