import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
process.on('uncaughtException',e=>{console.error(e.message,e.where||e.stack?.split('\n').slice(1,3).join('\n'));process.exit(1);});
const db=new PGlite();const checks=[];const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb,created_at timestamptz DEFAULT now());
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
-- Vault mock only for local call contracts: this fixture does NOT test encryption.
CREATE SCHEMA vault;CREATE TABLE vault.secrets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),secret text,name text);
CREATE VIEW vault.decrypted_secrets AS SELECT id,secret AS decrypted_secret FROM vault.secrets;
CREATE FUNCTION vault.create_secret(s text,n text) RETURNS uuid LANGUAGE plpgsql AS $$ DECLARE i uuid; BEGIN INSERT INTO vault.secrets(secret,name) VALUES(s,n) RETURNING id INTO i;RETURN i;END $$;`);
for(const f of ['001-base.sql','002-production-hardening.sql','003-campaign-lifecycle.sql'])await db.exec(read('../backend/supabase/'+f));
const fingerprint=async()=>(await db.query("SELECT jsonb_object_agg(proname,md5(pg_get_functiondef(p.oid))) h FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='outreach'")).rows[0].h;
const before=await fingerprint();
await db.exec(read('../backend/supabase/v2-foundation/001-identity.sql').replace('CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault;',''));
await db.exec(read('../backend/supabase/v2-foundation/002-private-saas-tables.sql'));
await db.exec(read('../backend/supabase/v2-review/004-isolated-storage.sql'));
await db.exec(read('../backend/supabase/v2-review/supabase-v2-runtime.sql'));
await db.exec(read('../backend/supabase/v2-review/007-active-connection-names.sql'));
await db.exec(read('../backend/supabase/v2-review/007-active-connection-names.sql'));
await db.exec(read('../backend/supabase/v2-review/008-private-connection-checks.sql'));
await db.exec(read('../backend/supabase/v2-review/008-private-connection-checks.sql'));
checks.push('Review schema and runtime SQL execute locally; Vault is mocked, not encryption-tested');
const personalized = await db.query("SELECT outreach.personalize($1, $2::jsonb) message", ['Hi {{first_name}}, I saw your company, {{company}}.', JSON.stringify({first_name:'Khurram', company:'ITB Solutions'})]);
assert.equal(personalized.rows[0].message, 'Hi Khurram, I saw your company, ITB Solutions.');
const secondPersonalized = await db.query("SELECT outreach.personalize($1, $2::jsonb) message", ['Hi {{first_name}}, I saw your company, {{company}}.', JSON.stringify({first_name:'Ali', company:'Sysnova Solutions'})]);
assert.equal(secondPersonalized.rows[0].message, 'Hi Ali, I saw your company, Sysnova Solutions.');
checks.push('The same first-name and company template produces distinct messages from each lead');

const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',viewer='33333333-3333-4333-8333-333333333333';
await db.query("INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES($1,'a@example.test','{}'),($2,'b@example.test','{}'),($3,'viewer@example.test','{}')",[a,b,viewer]);
const covered=new Set();let seq=0;const api=async(uid,p,proof={})=>{covered.add(p.action);return (await db.query('SELECT public.eb_outreach_api_v2($1,$2::jsonb,$3::jsonb) r',[uid,JSON.stringify({requestId:'runtime-fixture-'+(++seq),...p}),JSON.stringify(proof)])).rows[0].r;};
const w1=(await api(a,{action:'workspaceCreate',companyName:'Company A',timezone:'UTC'})).data.workspaceId;
const w2=(await api(b,{action:'workspaceCreate',companyName:'Company B',timezone:'UTC'})).data.workspaceId;
assert.ok(w1);assert.ok(w2);
const oldNamed=(await api(a,{action:'sessionCreate',workspaceId:w1,displayName:'Reusable connection'})).data.whatsappSessionId;
assert.equal((await api(a,{action:'sessionCreate',workspaceId:w1,displayName:'Reusable connection'})).success,false);
assert.equal((await api(a,{action:'sessionDelete',workspaceId:w1,whatsappSessionId:oldNamed})).success,true);
const newNamed=(await api(a,{action:'sessionCreate',workspaceId:w1,displayName:'Reusable connection'})).data.whatsappSessionId;
assert.ok(newNamed);assert.notEqual(newNamed,oldNamed);
const diagnostic=async(uid,phase,status,reason)=>(await db.query('SELECT public.eb_outreach_record_connection_check_v2($1,$2,$3,$4,$5,$6) r',[uid,newNamed,phase,status,reason,'fixture-check'])).rows[0].r;
assert.equal((await diagnostic(b,'identity',200,'user_missing_id')).error.code,'FORBIDDEN');
assert.equal((await diagnostic(a,'identity',200,'user_missing_id')).error.code,'PROVIDER_NOT_CONNECTED');
assert.equal((await diagnostic(a,'status',429,'status_http')).error.code,'PROVIDER_NOT_CONNECTED');
assert.equal((await diagnostic(a,'identity',408,'user_http')).error.code,'BACKEND_UNAVAILABLE');
assert.equal((await diagnostic(a,'identity',504,'user_http')).error.code,'BACKEND_UNAVAILABLE');
assert.equal((await diagnostic(a,'status',429,'status_http')).error.code,'PROVIDER_NOT_CONNECTED');
assert.equal((await diagnostic(a,'identity',200,'raw-provider-body')).error.code,'INVALID_REQUEST');
assert.equal((await diagnostic(a,null,200,'status_http')).error.code,'INVALID_REQUEST');
const metadata=(await db.query('SELECT * FROM outreach_v2.connection_checks WHERE whatsapp_session_id=$1',[newNamed])).rows;
assert.equal(metadata.length,1);assert.equal(metadata[0].workspace_id,w1);assert.equal(metadata[0].reason,'status_http');assert.equal(metadata[0].http_status,429);
assert.deepEqual(Object.keys(metadata[0]).sort(),['whatsapp_session_id','workspace_id','phase','http_status','reason','checked_at'].sort());
checks.push('Private connection checks enforce company membership, fixed metadata and one latest row; raw content rejected');
assert.equal((await db.query('SELECT deleted_at IS NOT NULL archived FROM outreach.whatsapp_sessions WHERE id=$1',[oldNamed])).rows[0].archived,true);
assert.equal((await api(a,{action:'sessionCreate',workspaceId:w1,displayName:'Reusable connection'})).success,false);
assert.equal((await api(a,{action:'sessionDelete',workspaceId:w1,whatsappSessionId:newNamed})).success,true);
checks.push('Archived connection names can be reused; active duplicates stay blocked and archived audit rows survive');
const boot=await api(a,{action:'bootstrap',userId:b});assert.equal(boot.data.user.userId,a);assert.equal(boot.data.workspaces.length,1);
assert.equal((await api(a,{action:'list',workspaceId:w2})).error.code,'FORBIDDEN');
await db.query("INSERT INTO public.workspace_members(workspace_id,user_id,role) VALUES($1,$2,'viewer')",[w1,viewer]);
assert.equal((await api(viewer,{action:'sessionCreate',workspaceId:w1,displayName:'Denied'})).error.code,'FORBIDDEN');checks.push('Auth-derived identity, company membership and viewer write restrictions verified');
const session=async(uid,w,name,phone)=>{
 const created=await api(uid,{action:'sessionCreate',workspaceId:w,displayName:name});assert.equal(created.success,true,JSON.stringify(created));
 const sid=created.data.whatsappSessionId;const key='fixture-api-secret-'+phone;const webhook='fixture-webhook-secret-'+phone;
 const connected=await api(uid,{action:'sessionConnect',workspaceId:w,whatsappSessionId:sid,apiSecret:key,webhookSecret:webhook},{status:'connected',phoneE164:phone});assert.equal(connected.success,true,JSON.stringify(connected));assert.ok(!JSON.stringify(connected).includes(key));return {sid,key,webhook};
};
const s1=await session(a,w1,'A first','+12025550191');const s2=await session(a,w1,'A second','+12025550192');const s3=await session(b,w2,'B first','+12025550193');
const listedSessions=(await api(a,{action:'sessionList',workspaceId:w1})).data;
assert.equal(listedSessions.length,2);assert.ok(listedSessions.every(s=>s.providerMode==='manual_session_key'));
assert.equal((await api(b,{action:'sessionList',workspaceId:w2})).data.length,1);
assert.equal(JSON.stringify((await db.query('SELECT request_body FROM outreach.api_requests_v2')).rows).includes('fixture-api-secret'),false);checks.push('Multiple numbers per company; API secrets omitted from response and idempotency cache');
const create=async(uid,w,s,phone)=>{
 const c=await api(uid,{action:'create',workspaceId:w,whatsappSessionId:s.sid,name:'Fixture Campaign',template:'Hello {{first_name}}',timezone:'UTC',sendingStartTime:'00:00',sendingEndTime:'00:00',sendIntervalSeconds:15});assert.equal(c.success,true,JSON.stringify(c));
 const cid=c.data.campaignId;assert.equal((await api(uid,{action:'import',workspaceId:w,campaignId:cid,contacts:[{name:'Fixture Person',firstName:'Fixture',company:'Example',phoneE164:phone}]})).success,true);
 assert.equal((await api(uid,{action:'start',workspaceId:w,campaignId:cid})).success,true);return cid;
};
const c1=await create(a,w1,s1,'+12025550201');const c2=await create(a,w1,s2,'+12025550202');const c3=await create(b,w2,s3,'+12025550203');
await db.exec('UPDATE outreach.sender_settings SET enabled=true');
assert.equal((await db.query('SELECT * FROM outreach.claim_next()')).rows.length,0);assert.deepEqual(await fingerprint(),before);checks.push('Legacy functions unchanged; v1 worker cannot claim any isolated customer messages');
const claimed=(await db.query('SELECT * FROM public.eb_outreach_claim_next_v2()')).rows.map(x=>Object.values(x)[0]);assert.equal(claimed.length,3);
assert.equal((await db.query('SELECT * FROM public.eb_outreach_claim_next_v2()')).rows.length,0);checks.push('Three sessions independently lease; each session allows only one active message');
for(const claim of claimed){
 const begun=(await db.query('SELECT public.eb_outreach_begin_send_v2($1,$2) r',[claim.messageId,claim.leaseToken])).rows[0].r;
 const expected=[s1,s2,s3].find(x=>x.sid===claim.whatsappSessionId);assert.equal(begun.apiSecret,expected.key);
 if(claim.campaignId===c3){await db.exec("UPDATE outreach_v2.messages SET lease_until=now()-interval '1 minute' WHERE status='dispatching'");continue;}
 const finish={messageId:claim.messageId,leaseToken:claim.leaseToken,outcome:'accepted',providerMessageId:'fixture-'+claim.messageId,safeResponse:{httpStatus:200,success:true}};
 assert.equal((await db.query('SELECT public.eb_outreach_finish_send_v2($1::jsonb) r',[JSON.stringify(finish)])).rows[0].r.saved,true);
 assert.equal((await db.query('SELECT public.eb_outreach_finish_send_v2($1::jsonb) r',[JSON.stringify(finish)])).rows[0].r.duplicate,true);
}
assert.equal((await api(a,{action:'detail',workspaceId:w1,campaignId:c1})).data.status,'completed');
assert.equal((await api(a,{action:'stop',workspaceId:w1,campaignId:c1})).data.status,'completed');assert.equal((await api(a,{action:'start',workspaceId:w1,campaignId:c1})).error.code,'CAMPAIGN_COMPLETED');
assert.equal((await api(a,{action:'delete',workspaceId:w1,campaignId:c1})).success,true);assert.equal((await api(a,{action:'delete',workspaceId:w1,campaignId:c1})).success,true);checks.push('Completion is immediate; stale Stop is successful; restart forbidden; repeated archive works');
await db.query('SELECT public.eb_outreach_maintenance_v2()');assert.equal((await db.query("SELECT count(*)::int n FROM outreach_v2.messages WHERE status='unknown'")).rows[0].n,1);
await db.exec("UPDATE outreach.session_sender_settings SET next_send_at=now()-interval '1 minute'");assert.equal((await db.query('SELECT * FROM public.eb_outreach_claim_next_v2()')).rows.length,0);checks.push('Expired dispatch becomes unknown and is never automatically resent');
const events=[{event_key:'reply-fixture',kind:'reply',provider_message_id:'inbound-fixture',phone:'+12025550202',text:'Hello',timestamp:new Date().toISOString(),opt_out:false}];
const ingest=async(s,sig,ev)=>(await db.query('SELECT public.eb_outreach_ingest_events_v2($1,$2,$3::jsonb) r',[s,sig,JSON.stringify(ev)])).rows[0].r;
assert.equal((await ingest(s2.sid,'wrong-secret-value',events)).success,false);assert.equal((await ingest(s2.sid,s2.webhook,events)).data.accepted,1);assert.equal((await ingest(s2.sid,s2.webhook,events)).data.accepted,0);
const inbox=(await api(a,{action:'inbox',workspaceId:w1})).data;const conv=inbox.find(x=>x.whatsappSessionId===s2.sid);assert.equal(conv.contact.name,'Fixture Person');
assert.equal((await api(a,{action:'reply',workspaceId:w1,conversationId:conv.conversationId,text:'Fixture reply',phoneE164:'+12025559999',whatsappSessionId:s1.sid})).success,true);
const reply=(await db.query('SELECT * FROM outreach_v2.messages WHERE campaign_id IS NULL')).rows[0];assert.equal(reply.whatsapp_session_id,s2.sid);assert.equal(reply.phone_e164,'+12025550202');checks.push('Webhook signature and duplicate protection; real contact names; reply routing derives from conversation');
const req={action:'saveTemplate',workspaceId:w1,requestId:'idempotent-fixture-001',name:'Test',body:'Hello {{name}}'};
assert.deepEqual(await api(a,req),await api(a,req));assert.equal((await api(a,{...req,body:'Different'})).error.code,'REQUEST_CONFLICT');
assert.equal((await api(b,{...req,workspaceId:w2})).success,true);checks.push('Write retries are repeat-safe, reject body conflicts, and scope request IDs by workspace');
assert.equal((await api(a,{action:'workspaceUpdate',workspaceId:w1,companyName:'Company A Updated',timezone:'UTC'})).success,true);
assert.equal((await api(a,{action:'profileUpdate',fullName:'Fixture Owner'})).data.fullName,'Fixture Owner');
for(const action of ['sessionStatus','messages','contacts','stats','templates','subscription','usage','health'])assert.equal((await api(a,{action,workspaceId:w1,...(action==='sessionStatus'?{whatsappSessionId:s1.sid}:{})})).success,true,action);
assert.equal((await api(a,{action:'conversation',workspaceId:w1,conversationId:conv.conversationId})).data.contact.name,'Fixture Person');
assert.equal((await api(a,{action:'markConversationRead',workspaceId:w1,conversationId:conv.conversationId})).data.unreadCount,0);
const c4=await create(a,w1,s2,'+12025550204');
assert.equal((await api(a,{action:'pause',workspaceId:w1,campaignId:c4})).data.status,'paused');
assert.equal((await api(a,{action:'resume',workspaceId:w1,campaignId:c4})).data.status,'running');
assert.equal((await api(a,{action:'stop',workspaceId:w1,campaignId:c4})).data.status,'stopped');
assert.equal((await api(a,{action:'suppress',workspaceId:w1,phoneE164:'+12025550204',reason:'Fixture opt-out'})).data.suppressed,true);
assert.equal((await api(a,{action:'delete',workspaceId:w1,campaignId:c4})).success,true);
await db.exec('UPDATE public.plans SET max_monthly_messages=2');
assert.equal((await db.query('SELECT * FROM public.eb_outreach_claim_next_v2()')).rows.length,0);
await db.exec('UPDATE public.plans SET max_monthly_messages=NULL');checks.push('Monthly cap prevents additional claims; pause/resume/stop/suppress transitions verified');
assert.equal((await api(a,{action:'sessionDisconnect',workspaceId:w1,whatsappSessionId:s1.sid})).success,true);
const disconnected=(await api(a,{action:'sessionList',workspaceId:w1})).data.find(s=>s.whatsappSessionId===s1.sid);
assert.equal(disconnected.configured,false);assert.equal(disconnected.providerMode,'manual_session_key');assert.equal(disconnected.status,'disconnected');
assert.equal((await api(a,{action:'sessionConnect',workspaceId:w1,whatsappSessionId:s1.sid,apiSecret:s1.key,webhookSecret:s1.webhook},{status:'connected',phoneE164:'+12025550191'})).success,true);
assert.equal((await db.query('SELECT enabled FROM outreach.session_sender_settings WHERE whatsapp_session_id=$1',[s1.sid])).rows[0].enabled,true);
const remove={action:'sessionDelete',workspaceId:w1,whatsappSessionId:s1.sid,requestId:'remove-session-fixture-001'};
assert.equal((await api(a,remove)).success,true);assert.equal((await api(a,remove)).success,true);assert.equal((await api(a,{...remove,requestId:'remove-session-fixture-002'})).success,true);
const expected=JSON.parse(read('../docs/saas-v2/test-payloads.json')).actions.map(x=>x.action);for(const action of expected)assert.ok(covered.has(action),'Missing action test: '+action);checks.push('All 31 public actions exercised; connection removal retries and reconnect sender state verified');
for(const role of ['anon','authenticated']){await db.exec('SET ROLE '+role);await assert.rejects(db.exec('SELECT * FROM outreach_v2.connection_checks'),/permission denied/);await assert.rejects(db.exec("SELECT public.eb_outreach_record_connection_check_v2(null,null,'status',200,'status_http','fixture')"),/permission denied/);await db.exec('RESET ROLE');}
await db.exec('SET ROLE authenticated');await assert.rejects(db.exec('SELECT * FROM outreach_v2.messages'),/permission denied/);await assert.rejects(db.exec("SELECT public.eb_outreach_api_v2('11111111-1111-4111-8111-111111111111','{}')"),/permission denied/);await db.exec('RESET ROLE');checks.push('Browser roles cannot read private queues or call trusted-backend RPCs');
console.log(JSON.stringify({passed:true,checks,publicActionsCovered:expected.length,noExternalCalls:true,vaultEncryptionTested:false,concurrentDatabaseTransactionsTested:false}));await db.close();
